### ISSUE TITLE
ParisKiwi

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#34]
https://gratipay.com/pariskiwi/

**Comment by chadwhitacre** [comment]
Not sure this one's a winner. Too much "anti-", especially anti-capitalist. Gratipay is [not anti-capitalist](http://blog.gittip.com/post/25215503687/corporations-and-open-ones/). We're actually actively [trying to work _within_ the existing global financial system](https://github.com/gratipay/inside.gratipay.com/issues/119) (aka, capitalism).

**Comment by mattbk** [comment]
In terms of [these criteria](https://github.com/gratipay/inside.gratipay.com/issues/311#issuecomment-130807380), these guys don't have a clear work-first plan--at least not linked on the application.

**Comment by mattbk** [comment]
The link to culture-jamming at http://inside.gratipay.com/big-picture/brand/ might invite anti-capitalists:

> We value honesty. We try to be honest with ourselves, and we welcome critique and [culture-jamming](https://en.wikipedia.org/wiki/Culture_jamming) of Gratipay by others.

(also, as noted elsewhere, my use of "work-first" is probably not the best.)

**Comment by chadwhitacre** [comment]
@mattbk Could you email the owner of this account to bring them into this conversation?

**Comment by mattbk** [comment]
Done.

**Comment by chadwhitacre** [comment]
Thanks. :-)

**Comment by smonff** [comment]
Thanks guys for reviewing our team membership.

Maybe my team membership application was a bit clumsy or not so serious.

I could maybe explain a bit about the _anti-_\* list we provide on our wiki: 2 years ago, some people starts to use our wiki to promote activities that didn't match with our philosophy. We provide this website to anybody willing to share informations about the Paris DIY musical scene, for free, without tracking anybody or selling data, and outside of the classical social networks. Our thinking about people (_punks_) who would define themselves as _anti-capitalist_ but would extensively use Facebook or MySpace for their promotion was that it didn't make sense. Even Bandcamp is non-acceptable sometimes, even if it is largely used by punk/alternative bands. Maybe it can be considered as as childish thinking, but we are a bit smarter that we look. For more, you can [read what we have to say about this](http://pariskiwi.org/index.php/Ni_myspace_ni_facebook) (FR). 

So we built this website using a vanilla Wikimedia. It is totally open to anybody. We almost moderate anything. Sometimes, when people promote very commercial stuff, or sexist stuff, we explain them that it is maybe not the better place for this and if really not acceptable, we delete the content. At some point, we experimented quite a lot of these kind of problems and decided to provide this _anti-_\* list, just to clearly say what we don't want here. These people were acting like if they posted cats on a website dedicated on dogs. 

We don't block or erase people  who link to Facebook or youtube or Bandcamp... People are free to do what they want. We are not so dumb. And we use a commercial hosting service and we drink commercial beer.

I don't think listing these _anti_ items was very smart: it is always more easy to say what you are against than what you are for. I agree with that.

Anyway here is a translation of what we stand up for : 
- creating a space for alternative / DIY practices around music and artistic stuff in Paris
- doing this in a participative way with a decentralized editing politic
- being autonomous and build our own communication tool (did you see as we are good at communicating :-D)
- creating sense
- being non-profit

So in the same time, this is logical : 
- we are not a website that will make money with it's activity
- we don't allow people to have a dominative, violent, sexist, homophobic, racist, ******\*  (this list could be longer) behavior while posting
- don't allow projects that don't create a form of _alternative_ (I agree it doesn't mean much but reading our website during two minutes makes it crystal clear if you can understand french)

I started to use Gratipay to support Riseup and some people of the Perl programing language community. At some point I think it was suitable for our project, maybe because of the values that you described as yours: gratitude, generosity, love, honesty, critique, kindness, collaboration and openness to one another. If I made a mistake we will find another way to retrieve money. You should understand that I used Gratipay because I identify it as an interesting alternative to other  (maybe it was a mistake).

About the _work-first plan_ and _open work_, here is how it is: you can find on http://pariskiwi.org a huge list of collectives, bands, labels. All these people work a lot, by crafting records, organize concerts, playing music, etc., together or not. For free, just because they like what they do. At some point, we built this to help all these people to coordinate themselves and help making visible and archiving a moving and sometimes ephemeral culture. It looks that after three years, it helps a bit and some people thanks us for maintaining this concert calendar. 

Thank you for reading and sorry for having being so long. At least it helps me to clarify our will :-D

**Comment by chadwhitacre** [comment]
@smonff Thanks for the thoughtful post! :-)

I'm reading through materials below the link you've shared, as well as the English Wikipedia article on [punk subculture](https://en.wikipedia.org/wiki/Punk_subculture):

> The punk subculture, which centres on punk rock music, includes a diverse array of ideologies, fashions and forms of expression, including visual art, dance, literature and film. The subculture is largely characterized by anti-establishment views and the promotion of individual freedom.

It's an interesting question, whether punk clashes too strongly with the Gratipay brand! I'm not sure yet, I have to observe and think about this more. In general, it seems fair to place Paris Kiwi within the punk subculture, yes?

> [W]e drink commercial beer.

Hah! Cheers! :D :beers:

**Comment by smonff** [comment]
ParisKiwi can be placed within the Punk subculture, but it is a bit restrictive. As I was explaining it in my previous message, these people much more describe themselves as belonging to the [DIY subculture](https://en.wikipedia.org/wiki/Do_it_yourself) - a 70's punk movement branch - that includes building fanzines, records, clothes, beer, vegetables or websites like ours and more... As you may know it, today, this movement is extremely diluted everywhere. All the movement around hackerspaces, 3D printing and the [instructables.com](http://instructables.com) website are good examples, most of these people [are not  punks](https://4.bp.blogspot.com/-gPpActojkUI/TWL9RDRBtEI/AAAAAAAAAHc/W-7UL7vRmkg/s1600/punk+6.jpg) though. I am not an historian, but maybe even the free software movement could have some shared roots with DIY.

**Comment by chadwhitacre** [comment]
Well, DIY _definitely_ belongs on Gratipay. We love hackerspaces and makers and DIYers! :-)

Thanks for working through this with us, @smonff. Welcome aboard Gratipay 2.0! :dancer: :beers:
