### ISSUE TITLE
KanColleWidget

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#38]
https://gratipay.com/kancollewidget/

@otiai10, your application be being reviewed here.

**Comment by otiai10** [comment]
Thank you! :satisfied:

**Comment by chadwhitacre** [comment]
Interesting. A cross-cultural review! :-)

First, a tweak: I believe the homepage should be http://otiai10.github.io/kanColleWidget/, because http://otiai10.github.io/kancollewidget gives me a 404 (GitHub pages are apparently case-sensitive).

Now, applying our [newly published review guidelines](http://inside.gratipay.com/howto/review-teams) ...
- [x] The Team must offer open work.
- [x] The Team must [be willing to eventually] participate in payroll.
- [ ] The Team must not clash too strongly with our [mission](http://inside.gratipay.com/big-picture/mission) and [brand values](http://inside.gratipay.com/big-picture/brand/).

The first two criteria are met: the first because it's an open-source project on GitHub, the second because of the checkbox on the new team form (I double-checked, and @otiai10 applied after we deployed [that](https://github.com/gratipay/gratipay.com/pull/3694)). However, I think the KanColle brand, which KanColleWidget participates in, clashes too strongly with the Gratipay brand.

#### KanColle is Sexist

From my point of view, [KanColle](https://en.wikipedia.org/wiki/Kantai_Collection) is blatantly sexist, focused as it is on "ship girls"—the ships that combat in the game are represented visually as women. An [image search](https://www.google.com/search?q=kancolle&tbm=isch), and a skim of [the wikia](http://kancolle.wikia.com/wiki/Kancolle_Wiki) and [the subreddit](https://www.reddit.com/r/kancolle/) confirm that the women are central to the game, not incidental.

[![screen shot 2015-08-24 at 9 55 11 am](https://cloud.githubusercontent.com/assets/134455/9441833/54dc18f8-4a46-11e5-9696-ecc9ac3c39dc.png)](https://www.google.com/search?q=kancolle&tbm=isch)

[![screen shot 2015-08-24 at 9 56 48 am](https://cloud.githubusercontent.com/assets/134455/9441915/9d3272d2-4a46-11e5-86f3-9e50dbebe8c6.png)](http://kancolle.wikia.com/wiki/Tutorial:_How_to_Play?file=KanColleFormation.png)

[![screen shot 2015-08-24 at 9 56 04 am](https://cloud.githubusercontent.com/assets/134455/9442268/0a2ee116-4a49-11e5-8451-790a0b99834e.png)](https://www.reddit.com/r/kancolle/comments/3i6wmi/achievement_this_girl_cost_me_my_sanitybut_its/)

Furthermore, a viewing of [a presumably representative play-through](https://www.youtube.com/watch?v=2AUQPRCbM50) discloses that the women are gradually disrobed as gameplay progresses. The martial violence of the game manifests in the suggestion of sexual violence against the women representing each ship. Here's a couple of representative before-and-afters:

![screen shot 2015-08-24 at 10 30 01 am](https://cloud.githubusercontent.com/assets/134455/9442811/c6fd427c-4a4b-11e5-88be-5c6b98f1c751.png)

![screen shot 2015-08-24 at 10 32 50 am](https://cloud.githubusercontent.com/assets/134455/9442819/d0c4bcb8-4a4b-11e5-9256-b7bc96ef873c.png)

![screen shot 2015-08-24 at 10 30 23 am](https://cloud.githubusercontent.com/assets/134455/9442831/e69f3fe0-4a4b-11e5-933c-2ee9150fb481.png)

![screen shot 2015-08-24 at 10 32 33 am](https://cloud.githubusercontent.com/assets/134455/9442839/ee6ee40a-4a4b-11e5-8bba-7205a365136c.png)

KanColle's use of hypersexualized women and sexual violence against women as central elements of its visual language constitute sexism, in my view.

#### Sexism Clashes with Gratipay

Sexism clashes strongly with the Gratipay [brand](http://inside.gratipay.com/big-picture/brand/), in particular, our values of **kindness**, **openness** to one another, and **safety**.

Hypersexualizing women and appropriating sexual violence as a gaming metaphor aren't kind! Gratipay wants to be kind. :-)

**Comment by otiai10** [comment]
Thank you for review, @whit537 :-)

> First, a tweak: I believe the homepage should be http://otiai10.github.io/kanColleWidget/, because http://otiai10.github.io/kancollewidget gives me a 404 (GitHub pages are apparently case-sensitive).

and I apologize my mistake in URL.

I was thinking "KanColleWidget" can be accepted because it is a mere wrapper for "KanColle" and has no own sexual expressions in it.

Now, I'm very appreciating your feedback and, in conclusion, I understand the conflict with Gratipay brand you pointed and it's reasonable to reject "KanColleWidget".

A bit sad but I'll try to apply another (kind, open and safe) project someday.

(application for "KanColleWidget" can be closed)

Thank you! ありがとう！

@otiai10

**Comment by chadwhitacre** [comment]
Thanks @otiai10. Hopefully in the future there will be a project of yours that is a good fit for Gratipay! :-)

**Comment by chadwhitacre** [comment]
For the record, the bad casing on the homepage URL was [our fault](https://github.com/gratipay/gratipay.com/pull/3719). Sorry! :-)

**Comment by otiai10** [comment]
Thanks for the announcement :+1:
