### ISSUE TITLE
searx

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#46]
https://gratipay.com/searx/

@asciimoo, your team application is being reviewed here.  It will be open for one week.

**Comment by chadwhitacre** [comment]
Looks great, I'd love to see this Team on Gratipay!

Minor detail: the to-do link is 404. Presumably it's supposed to be:

https://github.com/asciimoo/searx/issues

instead of:

https://github.com/asciimoo/issues

Yes, @asciimoo? I can change it for you since Teams aren't editable yet (https://github.com/gratipay/gratipay.com/issues/3545).

Other than that, I'll be happy to approve this next week in the absence of objections from others.

**Comment by asciimoo** [comment]
@mattbk, @whit537 thanks! =)
yes, the correct link is https://github.com/asciimoo/searx/issues, thank you the fix.

**Comment by chadwhitacre** [comment]
Fixed! :-)

**Comment by chadwhitacre** [comment]
Approved! Welcome aboard, @asciimoo! :dancer:

**Comment by asciimoo** [comment]
\o/
Thanks!

**Comment by mattbk** [comment]
@asciimoo, you can now edit your team info on the team page if you need to in the future.
